src/A04/Controllers/Team1Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace A04.Controllers
{
    public class Team1Controller : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult AnveshkumarKolluri()
        {
            return View();
        }
        public IActionResult ManindraNareshKumar()
        {
            ViewData["Title"] = "About Manindra Naresh Kumar";
            return View();
        }
        public IActionResult Saikrishna()
        {
            return View();
        }

        public IActionResult Jagadeesh()
        {
            ViewData["Title"] = "About Jagadeesh Basimsetty";
            return View();
        }

          public IActionResult ChandrakanthPodishetty()
        {

            return View();
        }
        public IActionResult RaihanAhmed()
        {
            ViewData["Title"] = "Raihan Ahmed's View Page";
            return View();
        }

    }
}

src/A04/Controllers/Team4Controller.cs


﻿using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace A04.Controllers
{
    public class Team4Controller : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult SatyaRadhaAddala()
        {
            ViewData["Title"] = "Team-4";
            ViewData["Protip"] = "Satya Radha Addala";
            return View();
        }

        public IActionResult Sandeep()
        {
            ViewData["Title"] = "Team-4";
            ViewData["Protip"] = "Sandeep Varma Rudraraju";
            return View();
        }
        public IActionResult Ramya()
        {
            ViewData["Title"] = "Team-4";
            ViewData["Protip"] = "Ramya V Sankara";
            return View();
        }
        public IActionResult Vamshinath()
        {
            ViewData["Title"] = "Team-4";
            ViewData["Protip"] = "Vamshinath";
            return View();
        }
        public IActionResult Kowshik()
        {
            ViewData["Title"] = "Team-4";
            ViewData["Protip"] = "Kowshik Morishetty";
            return View();
        }
    }
}

src/A04/Controllers/Team5Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace A04.Controllers
{
    public class Team5Controller : Controller
    {
        // GET: /Team/
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Ashishpandey()
        {
            ViewData["Title"] = "Ashish Pandey's View Page";

            return View();
        }

        public IActionResult NadeemAnsari()
        {
            ViewData["Title"] = "Nadeem Ansari's View Page";
            return View();
        }

        public IActionResult SupremRaju()
        {
            ViewData["Title"] = "Suprem Raju Manthena's View Page";
            return View();
        }

        public IActionResult Vijay()
        {
            ViewData["Title"] = "Vijay Gopi's Information.";
            return View();
        }

        public IActionResult Sharanya()
        {
            ViewData["Title"] = "Welcome to  My profile";
            return View();
        }
    }
}

src/A04/Controllers/TeamController.cs

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace A04.Controllers
{
    public class TeamController : Controller
    {
        // GET: /Team/
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Denisecase()
        {
            ViewData["Title"] = "Denise Case's View Page";
            ViewData["Protip"] = "Use CTRL-5 to save and refresh (rather than restarting).";

            return View();
        }

        public IActionResult KrishnaPainuly()
        {
            return View();
        }
     
        public IActionResult Manasabojja()
        {
            ViewData["Title"] = "Manasa Bojja's Page";

            return View();
        }
    }

}

src/A04/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - A04</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.5/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div id="fb-root"></div>
   
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-controller="Home" asp-action="Index" class="navbar-brand">Class View Practice</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav" style="align-content:flex-start">
                    <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-controller="Home" asp-action="Contact">Contact</a></li>
                    <!--Team-->
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Team
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a asp-controller="Team" asp-action="Denisecase">Denise Case</a></li>
                            <li><a asp-controller="Team" asp-action="KrishnaPainuly">Krishna Painuly</a></li>
                            <li><a asp-controller="Team" asp-action="Manasabojja">Manasa Bojja</a></li>

                        </ul>
                    </li>
                    <!--Team01-->
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Team 1
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a asp-controller="Team1" asp-action="AnveshkumarKolluri">Anveshkumar Kolluri</a></li>
                            <li><a asp-controller="Team1" asp-action="RaihanAhmed">Raihan Ahmed</a></li>
                            <li><a asp-controller="Team1" asp-action="Saikrishna">Saikrishna Chinthapatla</a></li>
                            <li><a asp-controller="Team1" asp-action="ChandrakanthPodishetty">Chandrakanth Podishetty</a></li>
                            <li><a asp-controller="Team1" asp-action="ManindraNareshKumar">Manindra Naresh Kumar Mamidibathula</a></li>
                            <li><a asp-controller="Team1" asp-action="Jagadeesh">Jagadeesh Babu Basimsetty</a></li>
                        </ul>
                    </li>

                    <!--Team02 -->
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Team 2
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">  
                            <li><a asp-controller="Team02" asp-action="BhavanaPilli">Bhavana Pilli</a></li>
                            <li><a asp-controller="Team02" asp-action="SowmyaLakkireddy">Sowmya Lakkireddy</a></li>
                            <li><a asp-controller="Team02" asp-action="KoppuNagaPrasad">Naga Prasad Gupta Koppu</a></li>
                            <li><a asp-controller="Team02" asp-action="RameshPasupuleti">Ramesh Pasupuleti</a></li>
                            <li><a asp-controller="Team02" asp-action="Imaduddin">Mohammad Imaduddin</a></li>
                        </ul>
                    </li>
                    <!--Team03-->
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Team 3
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a asp-controller="Team3" asp-action="Abhinaya">Abhinaya</a></li>
                            <li><a asp-controller="Team3" asp-action="Pranay">Pranay</a></li>
                            <li><a asp-controller="Team3" asp-action="SaiNaveen">Sai Naveen</a></li>


                            <li><a asp-controller="Team3" asp-action="">Manichandra</a></li>

                            <li><a asp-controller="Team3" asp-action="Mani">Manichandra</a></li>

                            <li><a asp-controller="Team3" asp-action="VeerapratapPutta">Veerapratap Putta</a></li>
                        </ul>
                    </li>

                    <!--Team04-->
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Fortis Five-Team4
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a asp-controller="Team4" asp-action="SatyaRadhaAddala">Satya Radha Addala</a></li>
                            <li><a asp-controller="Team4" asp-action="Kowshik">Kowshik  Morishetty</a></li>
                            <li><a asp-controller="Team4" asp-action="Vamshinath">Vamshinath Nallamothu</a></li>
                            <li><a asp-controller="Team4" asp-action="Sandeep">Sandeep Varma Rudraraju</a></li>
                            <li><a asp-controller="Team4" asp-action="Ramya">Ramya V Sankara</a></li>
                        </ul>
                    </li>


                    <!--Team05-->
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Team 5 - The Dark Knights
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a asp-controller="Team5" asp-action="Sharanya">Sharanya</a></li>
                            <li><a asp-controller="Team5" asp-action="Vijay">Vijay Gopi</a></li>
                            <li><a asp-controller="Team5" asp-action="NadeemAnsari">Nadeem Ansari</a></li>
                            <li><a asp-controller="Team5" asp-action="SupremRaju">Suprem Raju</a></li>
                            <li><a asp-controller="Team5" asp-action="Ashishpandey">Ashish Pandey</a></li>
                        </ul>
                    </li>

                    <!--Team06-->
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Team 6
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a asp-controller="Team6" asp-action="MohammedSardar">Mohammed Sardar</a></li>
                            <li><a asp-controller="Team6" asp-action="Satvik">Bhanu Satvik Reddy</a></li>
                            <li><a asp-controller="Team6" asp-action="Rohan">Rohanreddy Thummala</a></li>
                            <li><a asp-controller="Team6" asp-action="TarakeshGogi">Tarakesh Gogi</a></li>
                            <li><a asp-controller="Team6" asp-action="Kiran">Kiran Kumar</a></li>
                            <li><a asp-controller="Team6" asp-action="Prateek">Prateek Ravilla</a></li>
                        </ul>
                    </li>
                    <!--Team07-->
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Team 7 
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a asp-controller="Team7" asp-action="pradeep">Pradeep</a></li>
                            <li><a asp-controller="Team7" asp-action="Priyanka">Priyanka</a></li>
                            <li><a asp-controller="Team7" asp-action="Preethi">Preethi</a></li>
                            <li><a asp-controller="Team7" asp-action="Srikanth">Srikanth</a></li>
                            <li><a asp-controller="Team7" asp-action="manoj">Manoj</a></li>
                            <li><a asp-controller="Team7" asp-action="Rahul">Rahul</a></li>
                        </ul>
                    </li>
                    <!--Team08-->
                    
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content" style="margin-top: 6%">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2016 - A04</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/js/denisecase.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.1.4.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.5/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
        <script src="~/js/denisecase.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>